import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "blogK",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-FQJG4LWVG7"
        ></Script>
        <Script>
          window.dataLayer = window.dataLayer || []; function gtag()
          {dataLayer.push(arguments)}
          gtag('js', new Date()); gtag('config', 'G-FQJG4LWVG7');
        </Script>
      </head>
      <body>{children}</body>
    </html>
  );
}
